language: php

env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

php:
  - 7.1
  - 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpspec run
  - composer inspect

after_script:
  - php ocular.phar code-coverage:upload --access-token="your-token" --format=php-clover coverage.clover
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
